#!/bin/sh -e

case "$1" in
    configure|reconfigure)
        mkdir -p /var/lib/sane-web-client/jobs
        mkdir -p /var/lib/sane-web-client/work
        chown -R saned.saned /var/lib/sane-web-client
        systemctl enable sane-web-client
    ;;
esac
