#!/bin/sh -e

USER=scanpi
HOME=/var/opt/scanpi

case "$1" in
    remove)
        systemctl daemon-reload
    ;;

    purge)
        userdel -r -f $USER > /dev/null 2>&1
		rm -rf $HOME
    ;;

    disappear|upgrade|failed-upgrade|abort-install|abort-upgrade)
    ;;

    *) echo "$0: didn't understand being called with \`$1'" 1>&2
    ;;
esac

exit 0
