#!/bin/sh -e

USER=saned
HOME=/var/opt/scanpi

case "$1" in
    configure|reconfigure)
 		mkdir -p "$HOME/jobs"
        mkdir -p "$HOME/work"
		chown $USER.$USER -R $HOME

        systemctl daemon-reload
        systemctl enable --now scanpi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
